Classical_Music/urls.py
from django.urls import path, include

from rest_framework import routers

from . import views


urlpatterns = [
    path('', views.ClassicalMusic_home, name="ClassicalMusic_home"),
    path('add_musician/', views.ClassicalMusic_add_musician, name="ClassicalMusic_add_musician"),
    path('add_role/', views.ClassicalMusic_add_role, name="ClassicalMusic_add_role"),
    path('add_composition/', views.ClassicalMusic_add_composition, name="ClassicalMusic_add_composition"),
    path('add_multiple_movements/', views.ClassicalMusic_add_multiple_movements, name="ClassicalMusic_add_multiple_movements"),
    path('add_release/', views.ClassicalMusic_add_release, name="ClassicalMusic_add_release"),
    path('add_tracks/', views.ClassicalMusic_add_tracks, name="ClassicalMusic_add_tracks"),
    path('add_default_data/', views.ClassicalMusic_add_default_data, name="ClassicalMusic_add_default_data"),


    path('musicians/', views.ClassicalMusic_show_musicians, name="ClassicalMusic_show_musicians"),
    path('compositions/', views.ClassicalMusic_show_compositions, name="ClassicalMusic_show_compositions"),
    path('releases/', views.ClassicalMusic_show_releases, name="ClassicalMusic_show_releases"),
    path('roles/', views.ClassicalMusic_show_roles, name="ClassicalMusic_show_roles"),

    path('musician/<int:pk>/details/', views.ClassicalMusic_details_musician, name='ClassicalMusic_details_musician'),
    path('composition/<int:pk>/details/', views.ClassicalMusic_details_composition, name='ClassicalMusic_details_composition'),
    path('release/<int:pk>/details/', views.ClassicalMusic_details_release, name='ClassicalMusic_details_release'),

    path('musician/<int:pk>/edit/', views.ClassicalMusic_edit_musician, name='ClassicalMusic_edit_musician'),
    path('role/<int:pk>/edit/', views.ClassicalMusic_edit_role, name='ClassicalMusic_edit_role'),
    path('composition/<int:pk>/edit/', views.ClassicalMusic_edit_composition, name='ClassicalMusic_edit_composition'),
    path('composition/<int:c_pk>/movement/<int:m_pk>/edit/', views.ClassicalMusic_edit_movement, name='ClassicalMusic_edit_movement'),
    path('composition/<int:pk>/add_movements/', views.ClassicalMusic_add_additional_movement, name='ClassicalMusic_add_additional_movement'),
    path('release/<int:pk>/edit/', views.ClassicalMusic_edit_release, name='ClassicalMusic_edit_release'),
    path('release/<int:pk>/edit_tracks/', views.ClassicalMusic_edit_tracks, name='ClassicalMusic_edit_tracks'),
    path('release/<int:pk>/add_track/', views.ClassicalMusic_add_additional_track, name='ClassicalMusic_add_additional_track'),

    path('musician/<int:pk>/delete/', views.ClassicalMusic_delete_musician, name='ClassicalMusic_delete_musician'),
    path('role/<int:pk>/delete/', views.ClassicalMusic_delete_role, name='ClassicalMusic_delete_role'),
    path('composition/<int:pk>/delete/', views.ClassicalMusic_delete_composition, name='ClassicalMusic_delete_composition'),
    path('release/<int:pk>/delete/', views.ClassicalMusic_delete_release, name='ClassicalMusic_delete_release'),
    path('release/<int:r_pk>/track/<int:t_pk>/delete/', views.ClassicalMusic_delete_track, name='ClassicalMusic_delete_track'),
    path('composition/<int:c_pk>/movement/<int:m_pk>/delete/', views.ClassicalMusic_delete_movement, name='ClassicalMusic_delete_movement'),

    path('musician/search/', views.ClassicalMusic_search_musician, name='ClassicalMusic_search_musician'),
    path('composition/search/', views.ClassicalMusic_search_composition, name='ClassicalMusic_search_composition'),
    path('release/search/', views.ClassicalMusic_search_release, name='ClassicalMusic_search_release'),
    path('role/search/', views.ClassicalMusic_search_role, name='ClassicalMusic_search_role'),

    path('musician/<str:MBID>/search/', views.ClassicalMusic_search_details_musician, name='ClassicalMusic_search_details_musician'),

    path('api/v1/musicians/', views.ClassicalMusic_api_musician_collection, name='ClassicalMusic_api_musician_collection'),
    path('api/v1/musicians/<int:pk>/', views.ClassicalMusic_api_musician_single, name='ClassicalMusic_api_musician_single'),
    path('api/v1/compositions/<int:pk>/', views.ClassicalMusic_api_composition_single, name='ClassicalMusic_api_composition_single'),

    path('TESTapi/v1/musicians/', views.ClassicalMusic_TEST_api_musician_collection, name='ClassicalMusic_TEST_api_musician_collection'),
    path('TESTapi/v1/musicians/1/', views.ClassicalMusic_TEST_api_musician_single, name='ClassicalMusic_TEST_api_musician_single'),
    path('TESTapi/v1/compositions/1/', views.ClassicalMusic_TEST_api_composition_single, name='ClassicalMusic_TEST_api_composition_single'),
    path('TESTapi/v1/musicians/POST', views.ClassicalMusic_TEST_api_musician_collection_POST, name='ClassicalMusic_TEST_api_musician_collection_POST'),
    path('TESTapi/v1/musicians/1/DELETE', views.ClassicalMusic_TEST_api_musician_single_DELETE, name='ClassicalMusic_TEST_api_musician_single_DELETE'),
    path('TESTapi/v1/musicians/2/EDIT', views.ClassicalMusic_TEST_api_musician_single_POST, name='ClassicalMusic_TEST_api_musician_single_POST'),
]

Classical_Music/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
TYPE_CHOICES = [
    ('individual', 'individual'),
    ('ensemble', 'ensemble'),
]

ROLE_TYPE_CHOICES = [
    ('author_type', 'Composer, lyricist, etc'),
    ('performer', 'performer'),
]

# on_delete=models.SET_NULL, null=True

# Roles are aall the roles musicians can have. The author type roles like composer and the performer type roles like conductor or violin or orchestra
class Role(models.Model):
    role = models.CharField(max_length=120, verbose_name="Role", default="", blank=False, null=False)
    type = models.CharField(max_length=20,verbose_name="Type", choices=TYPE_CHOICES, blank=False, null=False)
    role_type = models.CharField(max_length=20,verbose_name="Type of contributor", choices=ROLE_TYPE_CHOICES, blank=False, null=False)

    def __str__(self):
        return self.role

#Musician can be an individual or an ensemble, it can be a composer, performer, conductor etc. This is the actual person or group
# For now a musician can have only one role.
class Musician(models.Model):
    name = models.CharField(max_length=120, verbose_name="Musician name", default="", blank=False, null=False)
    sort_name = models.CharField(max_length=120, verbose_name="Musician sort name", default="", blank=False, null=False)
    type = models.CharField(max_length=20,verbose_name="Type", choices=TYPE_CHOICES, blank=False, null=False)
    gender = models.CharField(max_length=120, verbose_name="Musician gender", default="", blank=True, null=False)
    role = models.ForeignKey(Role, on_delete=models.PROTECT, null=False)
    Life_begin = models.CharField(max_length=20, verbose_name="Life begin", default="", blank=True, null=False)
    Life_end = models.CharField(max_length=20, verbose_name="Life end", default="", blank=True, null=False)
    life_ended = models.BooleanField(verbose_name="Deceased/Dissolved", blank=True, null=True)
    image_url = models.CharField(max_length=260, verbose_name="Image URL", default="", blank=True, null=False)
    MBID = models.CharField(max_length=80, verbose_name="Musician MBID", default="", blank=True, null=False)

    def __str__(self):
        return self.name

# a composition can have many authors (composer and lyricist) and can have many roles (instrumentation)
class Composition(models.Model):
    title = models.CharField(max_length=180, verbose_name="Title", default="", blank=False, null=False)
    authors = models.ManyToManyField(Musician)
    instrumentation = models.ManyToManyField(Role)

    def __str__(self):
        return self.title


# If a composition has no movements the defualt is one movement
class Movement(models.Model):
    title = models.CharField(max_length=180, verbose_name="Movement Title", default="", blank=False, null=False)
    composition = models.ForeignKey(Composition, on_delete=models.CASCADE)
    order_number = models.IntegerField(verbose_name="#")

    def __str__(self):
        string = "{}: {}".format(self.composition, self.title)
        return string

class ReleaseManager(models.Manager):
    def compositions(self):
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT release.id, release.title, composition.id, composition.title, GROUP_CONCAT(DISTINCT author.name) AS author_names, GROUP_CONCAT(DISTINCT performer.name) AS performer_names, release.image_url

                FROM ClassicalMusic_release AS release
                LEFT OUTER JOIN ClassicalMusic_track as track ON release.id=track.release_id
                LEFT OUTER JOIN ClassicalMusic_movement as movement ON movement.id=track.movement_id
                LEFT OUTER JOIN ClassicalMusic_composition as composition ON composition.id=movement.composition_id
                LEFT OUTER JOIN ClassicalMusic_composition_authors AS comp_auth ON comp_auth.composition_id=composition.id
                LEFT OUTER JOIN ClassicalMusic_musician AS author ON comp_auth.musician_id=author.id
                
                LEFT OUTER JOIN ClassicalMusic_track_performers as track_perf ON track_perf.track_id=track.id
                LEFT OUTER JOIN ClassicalMusic_musician as performer ON track_perf.musician_id=performer.id
                
                GROUP BY release.id, composition.id
                ORDER BY release.title, release.id, composition.title
                """)
            result_list = []
            for row in cursor.fetchall():
                p = self.model(id=row[0], title=row[1])
                p.composition_id = row[2]
                p.composition_title = row[3]
                p.author_names = row[4]
                p.performer_names = row[5]
                p.image_url = row[6]
                result_list.append(p)
        return result_list

class Release(models.Model):
    title = models.CharField(max_length=180, verbose_name="Title", default="", blank=False, null=False)
    image_url = models.CharField(max_length=260, verbose_name="Cover art URL", default="", blank=True, null=False)
    objects = ReleaseManager()

    def __str__(self):
        return self.title



# recording are handled at the movement level, because sometimes only individual movements are recorded in stead of the entire composition
class Track(models.Model):
    movement = models.ForeignKey(Movement, on_delete=models.PROTECT)
    release = models.ForeignKey(Release, on_delete=models.CASCADE)
    performers = models.ManyToManyField(Musician)
    disk = models.CharField(max_length=180, verbose_name="Disk", default="", blank=False, null=False)
    track_number = models.IntegerField()

    def __str__(self):
        return "{}".format(self.movement)

Classical_Music/templates/ClassicalMusic/ClassicalMusic_TEST_api_add_musician.html
{% extends "ClassicalMusic/ClassicalMusic_base_jumbotron.html" %}
{% load staticfiles %}


{% block jumbotron %}
	<h2>Add Musician through API</h2>
    <form method="post" class="was-validated" action="http://127.0.0.1:8000/ClassicalMusic/api/v1/musicians/">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-custom-color">Save Musician</button>
        <a class="btn btn-custom-color float-right" href="{% url 'ClassicalMusic_show_musicians' %}">Cancel</a>

    </form>

{% endblock %}

Classical_Music/templates/ClassicalMusic/ClassicalMusic_add_multiple_movements.html
{% extends "ClassicalMusic/ClassicalMusic_base_jumbotron.html" %}
{% load staticfiles %}


{% block jumbotron %}
	<h2>Add Movements</h2>
    <h3>{{ composition }}</h3>
    <form method="post" class="was-validated">
        {% csrf_token %}
         {{ form.non_field_errors }}
         {{ formset.management_form }}
            {% for form in formset %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                <div class="form-row jumbotron-form">
                    {% for field in form.visible_fields %}
                        {% if field.label == "#" %}
                            <div class="form-group col-3">
                                {{ field.label }}
                                {{ field }}
                            </div>
                        {% elif field.label == "Movement Title" %}
                            <div class="form-group col-9">
                                {{ field.label }}
                                {{ field }}
                            </div>
                        {% elif field.label == "Composition" %}
                            <div class="form-group col-0">
                                {{ field }}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endfor %}
        <br>
        <button type="submit" class="btn btn-custom-color">Save Movements</button>
        <a class="btn btn-custom-color float-right" href="{% url 'ClassicalMusic_show_compositions' %}">Cancel</a>

    </form>

{% endblock %}


{% block javascript %}
    {{ block.super }}
    {# This script does not work if you put it in a .js file. It can't read the django variable then #}
    <script>
        $(".composition-prefill").val({{ composition.pk }})
    </script>
{% endblock %}

Classical_Music/templates/ClassicalMusic/ClassicalMusic_add_musician.html
{% extends "ClassicalMusic/ClassicalMusic_base_jumbotron.html" %}
{% load staticfiles %}


{% block jumbotron %}
	<h2>Add Musician</h2>

    <form method="post" class="was-validated">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <div id="form-part1">
            {% for field in form.visible_fields|slice:":5" %}
                {{ field.label }} {{ field }}
            {% endfor %}
            <br>
            <div class="button-container">
                <a class="btn btn-custom-color" href="{% url 'ClassicalMusic_show_musicians' %}">Cancel</a>
                <a class="btn btn-custom-color"  onclick="next_form('1')"><i class="fas fa-angle-right big-icon  icon"></i></a>
<!--                <a class="btn btn-custom-color"  id="next1">Next (event)</a>-->
            </div>
        </div>


        <div id="form-part2">
            {% for field in form.visible_fields|slice:"5:" %}
                {{ field.label }} {{ field }}
            {% endfor %}
            <br>
            <div class="button-container">
                <a class="btn btn-custom-color"  onclick="previous_form('2')"><i class="fas fa-angle-left big-icon icon"></i></a>
                <button type="submit" class="btn btn-custom-color">Save</button>
                <a class="btn btn-custom-color" href="{% url 'ClassicalMusic_show_musicians' %}">Cancel</a>
            </div>
        </div>



        <br><br>
        <div class="button-container">
            <a class="btn btn-custom-color" href="{% url 'ClassicalMusic_add_composition' %}">Composition</a>
            <a class="btn btn-custom-color" href="{% url 'ClassicalMusic_add_release' %}">Release</a>
            <a class="btn btn-custom-color" href="{% url 'ClassicalMusic_add_role' %}">Role</a>
        </div>
    </form>


<!--The below shows TEST for every field-->
<!--    <form method="post" class="was-validated">-->
<!--        {% csrf_token %}-->
<!--        {{ form.non_field_errors }}-->
<!--        {% for hidden in form.hidden_fields %}-->
<!--            {{ hidden }}-->
<!--        {% endfor %}-->
<!--        {% for field in form.visible_fields %}-->
<!--            {% if forloop.counter <= 4 %}-->
<!--                {{ field.label }} TEST {{ field }}-->
<!--            {% else %}-->
<!--                {{ field.label }} TEST {{ field }}-->
<!--            {% endif %}-->


<!--        {% endfor %}-->

<!--        <button type="submit" class="btn btn-custom-color">Save Musician</button>-->
<!--        <a class="btn btn-custom-color float-right" href="{% url 'ClassicalMusic_show_musicians' %}">Cancel</a>-->
<!--        <br><br>-->
<!--        <div class="button-container">-->
<!--            <a class="btn btn-custom-color" href="{% url 'ClassicalMusic_add_composition' %}">Composition</a>-->
<!--            <a class="btn btn-custom-color" href="{% url 'ClassicalMusic_add_release' %}">Release</a>-->
<!--            <a class="btn btn-custom-color" href="{% url 'ClassicalMusic_add_role' %}">Role</a>-->
<!--        </div>-->
<!--    </form>-->

<!--    <form method="post" class="was-validated">-->
<!--        {% csrf_token %}-->
<!--        {{ form.non_field_errors }}-->
<!--        {{ form.as_p }}-->
<!--        <button type="submit" class="btn btn-custom-color">Save Musician</button>-->
<!--        <a class="btn btn-custom-color float-right" href="{% url 'ClassicalMusic_show_musicians' %}">Cancel</a>-->
<!--        <br><br>-->
<!--        <div class="button-container">-->
<!--            <a class="btn btn-custom-color" href="{% url 'ClassicalMusic_add_composition' %}">Composition</a>-->
<!--            <a class="btn btn-custom-color" href="{% url 'ClassicalMusic_add_release' %}">Release</a>-->
<!--            <a class="btn btn-custom-color" href="{% url 'ClassicalMusic_add_role' %}">Role</a>-->
<!--        </div>-->
<!--    </form>-->

{% endblock %}

Classical_Music/templates/ClassicalMusic/ClassicalMusic_details_musician.html
{% extends "ClassicalMusic/ClassicalMusic_base_menu.html" %}

{% load staticfiles %}

{% block search_action %}
    {% url 'ClassicalMusic_search_musician' %}
{% endblock %}


{% block content %}

<header class="page_header">
    <h1>{{ musician }}</h1>
</header>

{% include "ClassicalMusic/includes/ClassicalMusic_errors.html" %}

<!--EDIT & DELETE BUTTONS BAND-->
<div class="d-flex justify-content-end">

</div>

<!-- ERRORS & BUTTONS BAND-->
<div class="button-container">
    <div>{% include "ClassicalMusic/includes/ClassicalMusic_errors.html" %}</div>
    <div >
    </div>
    <div>
        <a class="icon-link" href="{% url 'ClassicalMusic_edit_musician' musician.pk %}">
            <i class="far fa-edit big-icon icon"></i>
        </a>
        <a data-toggle="modal" data-target="#confirm_delete">
            <i class="far fa-trash-alt big-icon icon"></i>
        </a>
        <a class="edit_icon" href="{% url 'ClassicalMusic_add_musician' %}">
            <i class="far fa-plus-square big-icon"></i>
        </a>
    </div>
</div>

<!--DETAILS TABLE-->
<table class="table ">
    <tbody>
        <tr class="">
            <td class=" w-header h-minimum">Name</td>
            <td class="w-center h-minimum">{{ musician.name }} </td>
            <td class="w-image" rowspan="6"><img class="portret" src="{% if musician.image_url %}{{ musician.image_url }}{% else %}{% static 'ClassicalMusic/images/music-4661526_1920.jpg' %}{% endif %}"></td>
        </tr>
        <tr class="">
            <td class="  h-minimum" >Sort name</td>
            <td class="">{{ musician.sort_name }}</td>

        </tr>
        <tr class="">
            <td class="  h-minimum" >Type</td>
            <td class="">{{ musician.type }}{% if musician.gender %}, {{ musician.gender }}{% endif %}</td>

        </tr>
        <tr class="">
            <td class="  h-minimum">Role</td>
            <td class="">{{ musician.role }}</td>

        </tr>
        <tr class="">
            <td class="  h-minimum" >Life</td>
            <td class="">{{ musician.life_begin }} - {{ musician.life_end }}</td>

        </tr>

        {# Don't display the Works section if it is empty #}
        {% if musician.composition_set.all %}
            <tr class="">
                <td class=" h-auto" >Works</td>
                <td class="">
                    {% for composition in musician.composition_set.all %}
                        {{ composition.title }}
                        <br>
                    {% endfor %}
                </td>

            </tr>
        {% endif %}

        {# Don't display the Recordings section if it is empty #}
        {% if musician.track_set.all %}
            <tr class="">
                <td class=" h-auto" >Recordings</td>
                <td class="">
                    {% for track in musician.track_set.all %}
                        {{ track.movement }}
                        <br>
                    {% endfor %}
                </td>

            </tr>
        {% endif %}

        {# If no recordings and no compositions, include empty row with auto height to match vertical space of image #}
        {% if musician.track_set.all or musician.composition_set.all  %}
        {% else %}
            <tr >
                <td class=" h-auto"></td>
                <td></td>
            </tr>
        {% endif %}

    </tbody>
</table>

<!--CONFIRM DELETE MODAL -->
<div class="modal" id="confirm_delete">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Comfirm Deletion</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

        <!-- Modal body -->
        <div class="modal-body">
          Are you sure you want to delete '{{ musician }}' form the database?
        </div>

      <!-- Modal footer -->
      <div class="modal-footer">
          <form method="POST" action="{% url 'ClassicalMusic_delete_musician' musician.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger" >Delete</button>
              <button type="button" class="btn btn-custom-color" data-dismiss="modal">Cancel</button>
          </form>


      </div>

    </div>
  </div>
</div>

{% endblock %}

Classical_Music/templates/ClassicalMusic/ClassicalMusic_details_release.html
{% extends "ClassicalMusic/ClassicalMusic_base_menu.html" %}

{% load staticfiles %}


{% block search_action %}
    {% url 'ClassicalMusic_search_musician' %}
{% endblock %}


{% block content %}
<header class="page_header">
    <h1>{{ release }}</h1>
</header>

<!-- ERRORS & BUTTONS BAND-->
<div class="button-container">
    <div>{% include "ClassicalMusic/includes/ClassicalMusic_errors.html" %}</div>
    <div >
    </div>
    <div>
        <a class="icon-link" href="{% url 'ClassicalMusic_edit_tracks' release.pk %}">
            <i class="far fa-edit big-icon icon"></i>
        </a>
        <a data-toggle="modal" data-target="#confirm_delete">
            <i class="far fa-trash-alt big-icon icon"></i>
        </a>
        <a class="edit_icon" href="{% url 'ClassicalMusic_add_release' %}">
            <i class="far fa-plus-square big-icon"></i>
        </a>
    </div>
</div>

<!--MAIN TABLE-->
<table class="table ">
    <tr>
        <td class=" w-header h-minimum">Title</td>
        <td class="w-center h-minimum">
            {{ release }}
                <a class="icon-link" href="{% url 'ClassicalMusic_edit_release' release.pk %}">
                    <i class="far fa-edit icon"></i>
                </a>
        </td>
        <td class="w-image" rowspan="6"><img class="portret" src="{% if release.image_url %}{{ release.image_url }}{% else %}{% static 'ClassicalMusic/images/music-4661526_1920.jpg' %}{% endif %}"></td>
    </tr>
    <tr>
        <td class=" h-auto">Tracks</td>
        <td>

            <table class="nested-table">
                <tbody>
                    {% for track in release.track_set.all %}
                        {% ifchanged %}
                            <tr>
                                <td>Disk {{ track.disk }}</td>
                                <td colspan="3">
                                    <strong><a href="{% url 'ClassicalMusic_details_composition' track.movement.composition.pk %}">{{ track.movement.composition }}</a></strong><br>
                                    {% for author in track.movement.composition.authors.all %}
                                        {% if forloop.last %}
                                            <strong><a href="{% url 'ClassicalMusic_details_musician' author.pk %}">{{  author }}</a></strong> - <span class="role">{{ author.role|lower }}</span>
                                        {% else %}
                                            <strong><a href="{% url 'ClassicalMusic_details_musician' author.pk %}">{{  author }}</a></strong> - <span class="role">{{ author.role|lower }}</span>,
                                        {% endif %}
                                    {% endfor %}
                                </td>
                                <td>
                                    {% for performer in track.performers.all %}
                                        {% if forloop.last %}
                                            <strong><a href="{% url 'ClassicalMusic_details_musician' performer.pk %}">{{  performer }}</a> - <span class="role">{{ performer.role|lower }}</span></strong>
                                        {% else %}
                                            <strong><a href="{% url 'ClassicalMusic_details_musician' performer.pk %}">{{  performer }}</a> - <span class="role">{{ performer.role|lower }}</span></strong>,
                                        {% endif %}
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endifchanged %}
                        <tr>
                            <td></td>
                            <td>
                                {{ track.track_number }}
                            </td>
                            <td>
                                {{ track.movement.title }}
                            </td>
                            <td>
                                <a data-val1="{% url 'ClassicalMusic_delete_track' release.pk track.pk %}" data-modal_body_text="Are you sure you want to delete '{{ track.movement.title }}' from '{{ release }}'?" data-toggle="modal" data-target="#confirm_delete_pk">
                                    <i class="far fa-trash-alt icon"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>
            <a class="edit_icon" href="{% url 'ClassicalMusic_add_additional_track' release.pk %}">
                        <i class="far fa-plus-square "></i><span class="italic">&nbsp;Add track</span>
            </a>






        </td>
    </tr>

</table>

<!--CONFIRM DELETE RELEASE MODAL -->
<div class="modal" id="confirm_delete">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Comfirm Deletion</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

        <!-- Modal body -->
        <div class="modal-body">
          Are you sure you want to delete '{{ release }}' from the database?
        </div>

      <!-- Modal footer -->
      <div class="modal-footer">
          <form method="POST" action="{% url 'ClassicalMusic_delete_release' release.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger" >Delete</button>
              <button type="button" class="btn btn-custom-color" data-dismiss="modal">Cancel</button>
          </form>


      </div>

    </div>
  </div>
</div>


<!--CONFIRM DELETE TRACK MODAL -->
<div class="modal" id="confirm_delete_pk">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Comfirm Deletion</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

        <!-- Modal body -->
        <div class="modal-body">
            Text is set by jQuery

        </div>

      <!-- Modal footer -->
      <div class="modal-footer">
          <form method="POST" action="" class="delete_link">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger" >Delete</button>
              <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
          </form>


      </div>

    </div>
  </div>
</div>


{% endblock %}

Classical_Music/templates/ClassicalMusic/ClassicalMusic_edit_movement.html
{% extends "ClassicalMusic/ClassicalMusic_base_jumbotron.html" %}
{% load staticfiles %}


{% block jumbotron %}
	<h2>Edit Movement</h2>
    <h3>{{ composition }}</h3>
    <form method="post" class="was-validated">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-custom-color">Save Movement</button>
        <a class="btn btn-custom-color float-right" href="{% url 'ClassicalMusic_details_composition' composition.pk %}">Cancel</a>
    </form>

{% endblock %}